//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimKoyu_Ecom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetirBasvuru2
    {
        public int Id { get; set; }
        public string your_name { get; set; }
        public string your_email { get; set; }
        public Nullable<double> telefon_no { get; set; }
        public string ulke { get; set; }
        public string ikamet_sehri { get; set; }
        public string okul { get; set; }
        public string bolum { get; set; }
        public string lisans_onlisans { get; set; }
        public string mezun_sinif { get; set; }
        public string ngilizcesev { get; set; }
        public string yazilimdilleri { get; set; }
        public string linkedinurl { get; set; }
        public string basvuru_detaylari { get; set; }
        public string F15 { get; set; }
        public bool OlumluMu { get; set; }
        public int Note { get; set; }
        public bool Okundu { get; set; }
        public string User { get; set; }
    }
}
