//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimKoyu_Ecom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEgitim
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> Cv { get; set; }
        public Nullable<System.DateTime> Mulakat { get; set; }
        public Nullable<System.DateTime> Baslangic { get; set; }
        public Nullable<System.DateTime> Bitis { get; set; }
    }
}
